author = Artur Tarassow
email = atecon@posteo.de
version = 1.0
date = 2021-06-30
description = Cointegration with regime-shifts
tags = C53
min-version = 2021b
data-requirement = needs-time-series-data
public = estimateGH plotGH
help = gregory_hansen_help.txt
sample-script = gregory_hansen_sample.inp
data-files = joe96_data.gdt
